### ISSUE TITLE
안녕하세요 번역물 관련 질문입니다.

### ISSUE THREAD

**Issue by tempusertuna** [wariua/manpages-ko#1]
안녕하세요
연락방법을 찾을수없어 부득이하게 이슈로 등록해봅니다.

autotools로 인해서 고생하고 있는 초보입니다.

wariua 님이 예전에 http://sourceware.org/autobook/ 를 번역하여
http://wariua.springnote.com/pages/ 에 번역물을 남겨두었다는 글을 보았습니다.

github나 다른 사이트들을 검색하여보았지만, 번역물이 나오지 않아
혹시나 소장하고 계신다면 공유를 받을수있는지 알고 싶습니다.

감사합니다.

**Comment by wariua** [comment]
안녕하세요,

springnote가 닫힐 때 백업 해 둔 번역물들을 https://wariua.cafe24.com/ 로 조금씩 옮겼는데 autobook은 일부만 번역돼 있어서 "나중에 언제..."라며 미루고만 있네요.

혹시 튜토리얼 정도로 충분하다면 [autotut](https://wariua.cafe24.com/wiki/Autotut)를 참고하실 수 있습니다.

원하신다면 기존의 autobook 번역본을 보내 드릴 수 있습니다. HTML 파일 형식이고 3장에서 10장까지 번역돼 있습니다. 문장을 아직 다듬지 않아서 쉽게 읽히지 않을 수도 있습니다. 같은 아이디로 gmail.com으로 메일 보내 주시면 답장으로 보내 드리겠습니다.
